name: CI Docker

on:
  workflow_run:
    workflows: ["CI Test"]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Download workflow PR number artifact
      uses: dawidd6/action-download-artifact@v2.11.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: ci-test.yml
        run_id: ${{ github.event.workflow_run.id }}

    - name: Read PR number artifact
      id: pr_number
      uses: juliangruber/read-file-action@v1
      with:
        path: ./pr_number/pr_number.txt
    - name: Echo it
      run: echo "NUMBER [${{ steps.pr_number.outputs.content }}]"

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: moretonj/generate
        addLatest: true
        addTimestamp: true
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - run: echo 'Test CI workflow failed - not pushing to Docker.'
