name: CI Docker

on:
  workflow_run:
    workflows: ["CI Test"]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Generate Build Number
      id: build-number
      run: echo "::set-output name=number::$(date + '%Y-%m-%d')-$(gh pr view --json number -q .number || echo '')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: moretonj/generate
        tags: latest, ${{ steps.build-number.outputs.number }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test CI workflow failed - not pushing to Docker.'
