name: CI Docker

on:
  workflow_run:
    workflows: ["CI Test"]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: get-date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: moretonj/generate
        tags: v1, generate-${{ steps.get-date.outputs.date }}, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test CI workflow failed - not pushing to Docker.'
