name: CI Docker

on:
  workflow_run:
    workflows: ["CI Test"]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Get date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

    - name: Get PR number
      id: pr
      run: echo "::set-output name=number::$(gh pr view --json number -q .number || echo "")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: moretonj/generate
        tags: latest, ${{ steps.date.outputs.today }}-${{ steps.pr.outputs.number }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test CI workflow failed - not pushing to Docker.'
